# Database configuration
database:
  path: "storage/db/orchestrator.db"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# State configuration
states:
  onboarding:
    required_fields: []
    validations: [] 